let name="Shreyansh Jain";
let school="ABC School";
let grade="7th";
let section="A";
let rollno=707;
let math=99;
let eng=95;
let science=90;
console.log("    ",school,"Report Card");
console.log("     ----------------------");
console.log("Name-",name,"  Roll Number-",rollno);
console.log("Grade-",grade,"            Section-",section);
console.log("Results:-");
console.log("--------------------------");
console.log("|SUBJECT     |     MARKS  |");
console.log("--------------------------");
console.log("|English     |    ",eng,"    |");
console.log("|Maths       |    ",math,"    |");
console.log("|Science     |    ",science,"    |");
console.log("--------------------------");